### ISSUE TITLE
Dashes cause issues with search

### ISSUE THREAD

**Issue by RallerenP** [RallerenP/modsearchbot#1]
As seen in [this](https://reddit.com/r/skyrimmods/comments/p2dg8a/modsearchbot_has_been_enabled/h8jpnip/) thread, dashes causes the search to fail.

Nexus search doesn't support dashes in searches, and they should be removed from the search string before searching.

It's possible that there are other characters that this holds true for as well.

**Comment by JonathanFeenstra** [comment]
Instead of replacing specific special characters, maybe it would be better to use [`encodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) on the query, like the [Nexus Mods Discord bot](https://github.com/Nexus-Mods/discord-bot/blob/2230a4b3d980590c9de5e90354abde9d96b32580/src/api/nexus-discord.ts#L70-L76) does. That should resolve all URI-encoding related errors (I use a similar approach in [my Discord bot](https://github.com/JonathanFeenstra/discord-modlinkbot)).

**Comment by RallerenP** [comment]
@JonathanFeenstra Using encodeURI doesn't seem to do it. Perhaps I still want use it to prevent other potential errors, but I still need to replace "-" with ",", like Nexus does it on the site.

Maybe I'm just using it wrong 😅

**Comment by JonathanFeenstra** [comment]
Actually `encodeURI` does not encode certain characters like dashes, so that will not be enough. Alternatively you could [replace all special characters with commas using regular expressions](https://github.com/JonathanFeenstra/discord-modlinkbot/blob/0410ba7d067af17ea48dfe8531d19981d58654b3/core/aionxm.py#L44), which I did for my bot.
