### ISSUE TITLE
Skyrimvr subreddit support

### ISSUE THREAD

**Issue by Shizof** [RallerenP/modsearchbot#3]
Hello, I'm a moderator on skyrimvr subreddit and we would like support on r/skyrimvr. 

If possible without LE Skyrim search, so only SE Skyrim and Bing.
If not possible, same as skyrimmods sub's implementation is fine.

I see that Bing search brings results from www.nexusmods.com/skyrim/ as well. So if it's possible, nexus results from only www.nexusmods.com/skyrimspecialedition/ would be better. LE mods don't work on skyrimvr without porting.

**Comment by RallerenP** [comment]
Hey, @Shizof I can definently enable the bot for /r/skyrimvr with the features you'd like!

I do have some notes about the Bing search. Here is the list of sources that Bing would search through for /r/skyrimvr

* https://www.loverslab.com *
* https://www.nexusmods.com (Skyrim Special Edition only)
* https://www.afkmods.com *
* https://skyrimdatabase.blogspot.com
* https://skse.silverlock.org
* ~~https://www.moddb.com~~ (Disabled because it keeps returning irellevant results)
* https://bethesda.net * 
* https://www.moddrop.com
* http://tesalliance.org *
* https://vectorplexus.com *

\* Will occasionally cause non-skyrim results to be returned.

---

The Bing search is really meant to be a help for mistyped mods, and to support acronyms. It's not that great at getting 100% focused, on-topic results. In the future I will work to get better results, but it's not *super* high priority.

Also, keep in mind that for now the Bing search and Nexus search can be entirely unfiltered for adult content. Currently, I can entirely enable or disable adult content from being posted, and in the next update (coming very shortly) it will be possible to make the bot only respond with potentially NSFW links, if the post is marked as NSFW.

Untill then, should I let adult content be enabled on /r/skyrimvr, or disable it entirely? And in the next update, should the bot only be able to post NSFW links in NSFW threads?

I'll go ahead and enable the bot ASAP once you've responded :)

**Comment by Shizof** [comment]
Hey, thanks for the reply,

It's even ok for Bing to get stuff from https://www.nexusmods.com/skyrimspecialedition only as well. We really only have stuff there except a few very important mods that are only on github really.

You can let adult content be enabled for now. With the addition of filtering feature, posting NSFW links in NSFW threads would be better I think.

Thank you!

**Comment by RallerenP** [comment]
I've enabled the bot for skyrimvr, 

It only fetches results from the SE Nexus, and the Bing search is configured to only pull results from there aswell.

I've also enabled the update that is supposed to filter out adult content from being posted to SFW posts. It's not perfect, but it greatly reduces unintended posting of adult content. 

This is a new update, and this would be the first time my code for handling multiple subreddits at once is being tested at scale, so if you encounter any problems, feel free to message me about it. I'll also be monitoring and looking out for odd behavior from the bot when I have the time.

For now I'll close this issue :)

**Comment by RallerenP** [comment]
@Shizof Hey, I just wanted to get your input on an upcoming change. 

I added the NSFW filter a month back, but in that time a lot of people have gotten really bad search results because of it (People are intending to get NSFW mods, or mods are improperly tagged as NSFW on Nexus or Bing). As a reminder, the bot will only try to get NSFW results, if the thread is also marked NSFW.

So I'm implementing a new feature that will enable NSFW results in all threads, but will instead put these results behind a spoiler tag, accompanied by a warning that tagged results might be NSFW.

I can keep things as they are now for /r/skyrimvr, trying to filter out NSFW results entirely. But I can also enable the new spoiler tag system when ready.

Which system should I enable for /r/skyrimvr?

**Comment by Shizof** [comment]
Spoiler tag approach sounds good.
