### ISSUE TITLE
Modsearchbot with Morrowind mods and r/tes3mods

### ISSUE THREAD

**Issue by MacBone** [RallerenP/modsearchbot#4]
Heya! Could modsearchbot be modified to search for Morrowind mods on r/tes3mods?

**Comment by RallerenP** [comment]
Hey, yes I'll add /r/tes3mods to the bot once i get some spare time in the coming week!

I use Nexus and Bing search. The Nexus search simply uses the Nexus' built in search functionality, the exact same as the one on the Nexus website.

I use Bing search to handle misspellings or abbreviations, as well as provide results from sites other Nexus.

For Bing search, if you give me a list of websites to search from I'll add them to the Bing configuration. It works best for pages that are dedicated to Morrowind mods, like ``https://nexusmods.com/morrowind``. The way it works is that I basically tell Bing to only provide results from URLs that match the pattern I give it.

So ``nexusmods.com/morrowind/mods/*`` would work well, because all morrowind mods on Nexus would follow that pattern.

But ``moddb.com/mods/*`` wouldn't work very well, as that pattern could match all the mods on the moddb website.

If you don't have a list of sites, I can just add nexusmods to the Bing search, to handle misspellings or abbreviations that Nexus doesn't handle itself. I can also just disable Bing entirely.

**Comment by MacBone** [comment]
Oh, right on! Thank you so much!
You can add these sites:
https://www.nexusmods.com/morrowind
https://mw.modhistory.com/
fliggerty.comhttps://mw.moddinghall.com/
https://www.moddb.com/games/morrowind/mods



    On Friday, August 19, 2022 at 10:57:13 AM MDT, RallerenP ***@***.***> wrote:  
 
 


Hey, yes I'll add /r/tes3mods to the bot once i get some spare time in the coming week!

I use Nexus and Bing search. The Nexus search simply uses the Nexus' built in search functionality, the exact same as the one on the Nexus website.

I use Bing search to handle misspellings or abbreviations, as well as provide results from sites other Nexus.

For Bing search, if you give me a list of websites to search from I'll add them to the Bing configuration. It works best for pages that are dedicated to Morrowind mods, like https://nexusmods.com/morrowind. The way it works is that I basically tell Bing to only provide results from URLs that match the pattern I give it.

So nexusmods.com/morrowind/mods/* would work well, because all morrowind mods on Nexus would follow that pattern.

But moddb.com/mods/* wouldn't work very well, as that pattern could match all the mods on the moddb website.

If you don't have a list of sites, I can just add nexusmods to the Bing search, to handle misspellings or abbreviations that Nexus doesn't handle itself. I can also just disable Bing entirely.

**Comment by RallerenP** [comment]
It should be set up now, sorry for the delay. 

I couldn't add morrowing moddb, as the mods pages themself use an URL pattern that wouldn't work very well. Including it would mean searching the entire moddb, and not just for morrowind mods.

Occasionally Reddit glitches out and doesn't tell the bot that a post or comment has been created, especially on older posts. But it *should* work 99% of the time on newer posts. You'll know if Reddit hasn't told the bot about a comment or post, if it doesn't respond at all to a summon.

When something goes wrong with the search, it'll just say "An error has occurred :(". Usually this means that Nexus or Bing is having problems, or that the server I'm hosting on is having connectivity issues. This will usually resolve itself after a little while.

Finally, I've given the bot the default configuration of searching for NSFW mods freely on NSFW posts, but I'll prioritise SFW mods on post without the NSFW flair (NSFW mods *will* be searched for, but they'll be in a separate table, behind spoiler tags). I can change this to entirely disable NSFW mod searching, or to enable it completely on all posts.

If you have any problems or questions, feel free to ask here on Github or by messaging me through /u/RallerenP on Reddit

**Comment by MacBone** [comment]
Thank you so much! I’ll add it to the subreddit and try it out right away.
